create or replace view v_ua_oprspecs as
select SH.rn,                       --1
       SH.prn,                      --2
       SH.company,                  --3
       SH.operation_date,           --4
       SH.currency,                 --5
       SH.balunit_debit,            --6
       SH.account_debit,            --7
       SH.account_debit_currency,   --8
       SH.nbalunit_debit,           --9
       SH.sbalunit_debit,           --10
       SH.analytic_debit1,          --11
       SH.analytic_debit2,          --12
       SH.analytic_debit3,          --13
       SH.analytic_debit4,          --14
       SH.analytic_debit5,          --15
       SH.balunit_credit,           --16
       SH.account_credit,           --17
       SH.account_credit_currency,  --18
       SH.analytic_credit1,         --19
       SH.analytic_credit2,         --20
       SH.analytic_credit3,         --21
       SH.analytic_credit4,         --22
       SH.analytic_credit5,         --23
       SH.nbalunit_credit,          --24
       SH.sbalunit_credit,          --25
       SH.acnt_sum,                 --26
       SH.acnt_base_sum,            --27
       SH.acnt_quant,               --28
       SH.acnt_alt_quant,           --29
       SH.acnt_equal,               --30
       SH.ctrl_sum,                 --31
       SH.ctrl_base_sum,            --32
       SH.ctrl_quant,               --33
       SH.ctrl_alt_quant,           --34
       SH.ctrl_equal,               --35
       SH.nomen_code,               --36
       SH.nomen_name,               --37
       SH.nomen_meas,               --38
       SH.nomen_ameas,              --39
       SH.nomen_partno,             --40
       SH.nomen_indate,             --41
       SH.nomen_crn,                --42
       SH.alt_sign1,                --43
       SH.alt_sign2,                --44
       SH.alt_sign3,                --45
       SH.alt_sign4,                --46
       SH.alt_sign5,                --47
       SH.alt_sign6,                --48
       SH.alt_sign7,                --49
       SH.alt_sign8,                --50
       SH.alt_sign9,                --51
       SH.alt_sign10,               --52
       SH.order_rn,                 --53
       SH.order_numb,               --54
       SH.record_type,              --55
       SH.dopercards_charge,        --56
       SH.nacctypes,                --57
       SH.sacctypes_code,           --58
       SH.nacctypes_type,           --59
       SH.sacctypes_currency,       --60
       SH.nacnt_acctypes_sum,       --61
       SH.nctrl_acctypes_sum,       --62
       M.crn,                       --63
       M.njur_pers,                 --64
       M.sjur_pers,                 --65
       M.operation_pref,            --66
       M.operation_numb,            --67
       M.operation_contents,        --68
       M.special_mark,              --69
       M.valid_doctype,             --70
       M.valid_docnumb,             --71
       M.valid_docdate,             --72
       M.fact_doctype,              --73
       M.fact_docnumb,              --74
       M.fact_docdate,              --75
       M.agent_from,                --76
       M.agent_to,                  --77
       M.crn_from,                  --78
       M.crn_to,                    --79
       M.acnt_opersum,              --80
       M.ctrl_opersum,              --81
       M.special_mark_rn,           --82
       M.valid_doctype_rn,          --83
       M.fact_doctype_rn,           --84
       M.agent_from_rn,             --85
       M.agent_to_rn,               --86
       M.eo_in,                     --87
       M.eo_out,                    --88
       M.nescort_doctype,           --89
       M.sescort_doctype,           --90
       M.sescort_docnumb,           --91
       M.descort_docdate            --92
  from V_OPRSPECS SH, V_ECONOPRS M where SH.PRN = M.RN;
